- name: Set up the role
  ansible.builtin.include_tasks:
    file: setup.yml

- name: Pull in the main role
  ansible.builtin.include_tasks:
    file: primary.yml

- name: Pull in all dependencies
  ansible.builtin.include_tasks:
    file: roledeps.yml

- name: Clean up after role
  ansible.builtin.include_tasks:
    file: cleanup.yml
