# If we are handed a rolespec structure then
# build out a temp requirements.yml file
- name: Only continue if we weren't passed information we need
  assert:
    that: (rolespec is defined) or (role_to_run is defined)
    quiet: true
    fail_msg: One of rolespec or role_to_run must be defined
    success_msg: We are good to move forward

- block:
    - name: Create temp requirements.yml file
      ansible.builtin.tempfile:
        state: file
        suffix: .yml
      register: t_reqfile

    - name: Template out the temporary requirements file
      ansible.builtin.template:
        src: reqfile.j2
        dest: "{{ t_reqfile.path }}"

  when: rolespec is defined
